name: docdoc
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.8
  # Simple direct Service Locator that allows to access the concrete implementation from everywhere
  get_it: ^7.6.4
  # State management
  flutter_bloc: ^8.1.3
  # Code generator (mainly used with Cubit & retrofit)
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  # Networking
  dio: ^5.3.4
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.6
  pretty_dio_logger: ^1.3.1
  # Localization
  intl: ^0.18.0
  easy_localization: ^3.0.3
  # For splash screen
  flutter_native_splash: ^2.3.9
  # An SVG rendering and widget library for Flutter, which allows painting
  flutter_svg: ^2.0.9
  # A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.9.0
  # Updating app's launcher icon
  flutter_launcher_icons: ^0.13.1
  # Flutter plugin for reading and writing simple key-value pairs for cache
  shared_preferences: ^2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Recommended lints to encourage good coding practices
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_assets:
  assets_path: assets/
  output_path: lib/src/core/utils/
  filename: app_assets.dart
  field_prefix: null
